name: mobile_system_proxy
description: A new Flutter plugin.
version: 0.1.0+1
author: akiberq@gmail.com
homepage: https://github.com/iKrupp/mobile_system_proxy

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.ikrupp.mobile_system_proxy
    pluginClass: MobileSystemProxyPlugin